### ISSUE TITLE
Expandable query area for larger queries 

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#100]
A Hosted Dolt customer would like the query area in the workbench UI to be expandable vertically so that larger queries (e.g. complex analytic queries) could be visible in the UI. This change would be applicable to DoltHub, too, but specifically calling it out as a Hosted Dolt feature, since that's what this customer uses.

**Comment by tbantle22** [comment]
The sql editor can expand up to 20 lines now. LMK if they need more than that
<img width="1714" alt="Screen Shot 2023-07-11 at 4 47 59 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/a088145f-ffd7-4937-a05e-d4f2c94a8817">
