### ISSUE TITLE
CSV file upload issue

### ISSUE THREAD

**Issue by subhra78** [dolthub/hosted-issues#101]
Tried to insert data using csv file but it throws error `Connection lost: The server closed the connection.`
https://drive.google.com/drive/folders/1k71PBXVo8oe-fIbl6QwAqD3jWrbVjD2Q?usp=sharing

**Comment by tbantle22** [comment]
Hi @subhra78, you can get that error for the following reasons:
- network problems
- the server timing you out
- the server being restarted or crashing

Do you get that error every time you try the upload? The graphs in the Monitoring tab also may provide more information
