### ISSUE TITLE
Feature: Show database tags in Hosted Dolt Workbench UI

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#104]
A Hosted Dolt customer requested the ability to see a list of the database's tags somewhere in the Workbench UI, as well as the ability to easily create new tags from the UI. Being able to click on a tag and run a sample query with it could be a nice touch to help customers start querying with the tag, too. One idea for the UI could be a new "tab" at the top of the Workbench UI, perhaps between "Commit Log" and "Releases".

**Comment by tbantle22** [comment]
We don't distinguish between releases and tags on DoltHub or the Hosted workbench. The release tab on the workbench uses the dolt_tags table to display the list of releases. If you click on a release you should be able to run queries against that tag

**Comment by fulghum** [comment]
Oh, you're right! The customer and I both totally missed that the "Releases" tab is where tags are listed.

It's probably worth considering changing the tab to either "Tags" or maybe "Releases / Tags" or something to make it more obvious to customers, or at minimum changing some text on the page to make it super obvious that those are tags. The customer and I both assumed "Releases" were a separate concept from "Tags". Using the same terminology for tags everywhere (CLI, DoltHub, Hosted Dolt) seems like it would make it easier for customers to figure out.

**Comment by timsehn** [comment]
GitHub intermingles releases/tags. That is why we do it.

**Comment by fulghum** [comment]
True, although GitHub does still distinguish between Tags and Releases as different concepts – Releases have extra metadata, release notes, downloadable artifacts, etc. There's also a large switcher button at the top of the GitHub releases page that makes it very obvious whether you're looking at Releases or Tags. Hitting the "Tags" button on that switcher even takes you to a different resource path (`/tags` instead of `/releases`). GitHub also provides a direct link to that tags page (which only shows tags and not releases) at the very top of a repo's main page. 

Since Dolt doesn't have separate concepts of Releases and Tags, it seems more intuitive for customers to just call them tags.

**Comment by tbantle22** [comment]
Would it help if this branch dropdown showed branches and tags? That's been on our dolthub list for a while
<img width="384" alt="Screen Shot 2023-07-07 at 9 43 27 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/0e3f442a-2df2-4dc4-b9b1-e56c1478bfdd">
Can look like this (but tags instead of commits)
<img width="423" alt="Screen Shot 2023-07-07 at 9 44 13 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/20203137-739f-4127-a3a0-cb0551939dd6">

**Comment by tbantle22** [comment]
GitHub has a similar UI
<img width="352" alt="Screen Shot 2023-07-07 at 9 51 50 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/bd224d51-06f6-4b4d-9459-bbd589852822">

**Comment by fulghum** [comment]
Cool idea to follow GitHub's design there and include branches and tags in the drop down. I think that would definitely help make tags more discoverable in the UI.

**Comment by tbantle22** [comment]
This is live now
<img width="436" alt="Screen Shot 2023-07-10 at 3 08 24 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/c5e41154-23be-4eef-9f36-040b8c2340e4">

**Comment by fulghum** [comment]
Thanks @tbantle22! Resolving this one now since tags are more prominent in the UI now, and using the "view all tags" link you added takes you to the tags page where you can create a new tag.
