### ISSUE TITLE
Workbench Queries Timeout too Quickly 

### ISSUE THREAD

**Issue by bheni** [dolthub/hosted-issues#105]
When using the SQL workbench queries timeout if not completed within 15 seconds.  We should increase the time we allow queries to run by default (maybe 1 minute), and ideally we would allow users to configure a timeout for their sql queries. Also in the event of a timeout it might be worthwhile to tell users that should try their query with the mysql command line client.

**Comment by Cazza1965** [comment]
I'm just a workbench user. Where do I create a support ticket? my workbench has stopped working. I sign in write an SOQL query but then it jumps straight back to the signin page

**Comment by timsehn** [comment]
@Cazza1965 You can make a new ticket in this repo or you can go to the support tab on your deployment and make a ticket there. That said @tbantle22 can help you debug. She owns the workbench.

**Comment by tbantle22** [comment]
We increased the timeout to 60s
