### ISSUE TITLE
Feature: Branch management UI 

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#106]
A Hosted Dolt customer mentioned that having a UI for create/delete branches in the Workbench UI would be helpful. This is not blocking customers from managing branches, but it does seem like a nice UI enhancement. 

As a workaround, for any customers who find this, you can use [the `dolt_branch` stored procedure to create or delete branches](https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures#dolt_branch).

**Comment by tbantle22** [comment]
Pretty sure this already exists for the workbench. Writes must be enabled for the deployment and the user needs to have write perms

**Comment by fulghum** [comment]
Oh, you're right! The customer and I both totally missed that the "Releases" tab is where tags are listed. 

It's probably worth considering changing the tab to either "Tags" or maybe "Releases / Tags" or something to make it more obvious to customers, or at minimum changing some text on the page to make it super obvious that those are tags. The customer and I both assumed "Releases" were a separate concept from "Tags". Using the same terminology for tags everywhere (CLI, DoltHub, Hosted Dolt) seems like it would make it easier for customers to figure out.

**Comment by fulghum** [comment]
Ah, I see the "+" button to create a new branch. That's great to have that. Being able to delete branches, too, would be nice, but that seems lower priority.

**Comment by tbantle22** [comment]
You can delete branches from the branch list page (clicking on view all branches from the branches drop-down) or from a closed/merged pull request

**Comment by fulghum** [comment]
Ah! You are totally right! Sorry that the customer and I both missed that. Thank you!
