### ISSUE TITLE
When submitting an SOQL query, workbench jumps back to the signon screen

### ISSUE THREAD

**Issue by Cazza1965** [dolthub/hosted-issues#108]
My workbench has stopped working. 
I sign in
Jump to SOQL query
Format the query
Click query 
 
and I'll sent back to the signon screen
It was working a week aho and has started misbehaving today

**Comment by tbantle22** [comment]
Looking into this today

**Comment by Cazza1965** [comment]
Thanks

**Comment by tbantle22** [comment]
Hi @Cazza1965, I was not able to reproduce this behavior. Can you give me more information about the query you're trying to run and what browser you're using?

If you'd like to discuss privately you can email me at taylor@dolthub.com or reach out to be on our [Discord](https://discord.gg/gqr7K4VNKe) (I'm @taylorb)

**Comment by Cazza1965** [comment]
It's any table that I try to query and I'm using Chrome Version 114.0.5735.199 (Official Build) (64-bit)
Is there a log that I can check for any errors that might be kicking me out?

**Comment by Cazza1965** [comment]
It's happening in Edge as well. Sometimes I get as far as the SOQL query setup and other times I get kicked out as soon as I try to jump to the SOQL query screen

**Comment by tbantle22** [comment]
So you're logging in, navigating to the workbench, running a select query on a table, and then it kicks you out to the sign in page?

Does this happen on any other page, like clicking on different deployment or workbench tabs? Or is it only when you run a query from the workbench?

Your browser console might give some hints. Do you have any cookie or popup blockers enabled? It isn't recognizing that you're signed in for some reason

**Comment by Cazza1965** [comment]
I'm not even getting to run the query. As soon as I click the QUERY button from the screen, I get kicked back to the sign on screen again. We have loads of blockers. This is a corporate site which is very tighty regimented. It's strange that I can sign on at first though and it lets me onto the site. I tried again with the console inspect on and now I'm getting the following error 

ERROR:
UNKNOWN ERROR: read error on connection to ec2-34-194-152-137.compute-1.amazonaws.com:6379

Do you have Ads in Workbench that perhaps we ae blocking?

**Comment by Cazza1965** [comment]
OK just tried again and now getting the same issue where I'm getting kicked out back to the sign on screen

**Comment by tbantle22** [comment]
We don't have any ads. But if you have an ad blocker that also prevents cookies I would expect issues like this. We rely on a cookie called `hostedToken` to know if a user has an active session.

Can you inspect your cookies and try running the query again? `hostedToken` shouldn't change when you run the query
<img width="1198" alt="Screen Shot 2023-06-29 at 10 25 40 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/ddbaeeae-c787-4126-9150-84adc954a486">

**Comment by tbantle22** [comment]
User was using a different workbench
