### ISSUE TITLE
Hosted as Remote: Clone/fetch/push/pull from a running hosted instance

### ISSUE THREAD

**Issue by timsehn** [dolthub/hosted-issues#11]
This will require running a doltremoteapi on a different port on the instance.

**Comment by tbantle22** [comment]
We now support read remote operations (clone, push, fetch) from a running hosted instance (but not push yet). More info here: https://www.dolthub.com/blog/2023-04-17-cloning-a-hosted-database/

**Comment by tbantle22** [comment]
Push was implemented in dolt v1.30.0
