### ISSUE TITLE
Restart Dolt Button

### ISSUE THREAD

**Issue by timsehn** [dolthub/hosted-issues#110]
We need a way on the hosted UI for the user to trigger a Dolt restart and potentially and instance restart.

**Comment by tbantle22** [comment]
This should be live early next week

**Comment by tbantle22** [comment]
Restart Dolt and Reboot instance are now available from the Actions dropdown
<img width="542" alt="Screen Shot 2023-07-11 at 1 52 25 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/4e548af9-7891-4dca-9b98-9f008acacb01">
