### ISSUE TITLE
Create a backup on demand

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#113]
A Hosted Dolt customer would like to explicitly create a backup in their deployment. In this case, it's because they want to create a new deployment from an existing deployment (with a larger instance size) and they want to backup all the changes they've made today so that the new deployment starts up with them. 

It would be ideal if there were a button in the "Backups" tab of the Hosted Dolt Deployment detail page that allowed users to create a new backup and also if there were a way to create a new backup from SQL by calling `dolt_backup`. If the SQL support is hard for whatever reason, the web UI button would definitely be sufficient.

**Comment by tbantle22** [comment]
The web UI button should be live early next week

**Comment by tbantle22** [comment]
You can now manually create a new backup from the Backups tab. Note that we only keep the most recent 14 backups
<img width="1302" alt="Screen Shot 2023-07-11 at 12 33 51 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/56360ba8-16c0-4121-8655-872177627355">
