### ISSUE TITLE
Add a developer collaborator permission level

### ISSUE THREAD

**Issue by Kelley12** [dolthub/hosted-issues#123]
**Is your feature request related to a problem? Please describe.**

When we add new users to our hosted dolt instance there are only two options `read` and `admin`. We initially gave everyone that doesn't need admin access read access. But with read access they can't do the things we need them to be able to do such as view and merge PR's. In order to do that right now, we have to grant admin access.

**Describe the solution you'd like**

A new permission level `developer` added to the Collaborators section. This permission level would give users access to the types of things developers would need: workbench, databases, view/create/merge PR's.

**Describe alternatives you've considered**

Right now the only workaround we have found is giving all of our developers `admin` access

**Additional context**

![Screenshot 2023-08-09 at 7 04 49 AM](https://github.com/dolthub/hosted-issues/assets/3813929/faeadc59-a532-4548-b69c-29764f38bf71)

**Comment by tbantle22** [comment]
This can be similar to the `write` permission we have on dolthub. They would have full write access via the workbench but no access to deployment actions/settings/configuration/connectivity info. Is that what you were thinking?

**Comment by Kelley12** [comment]
Yeah that's what I had in mind. That would work great.
