### ISSUE TITLE
Auto delete branch on successful merge

### ISSUE THREAD

**Issue by Kelley12** [dolthub/hosted-issues#133]
**Is your feature request related to a problem? Please describe.**
Not a problem other than our own forgetting to delete the branch following a merge

**Describe the solution you'd like**

An option on the PR to auto delete the branch on successful merge?

Similar to this one GitLab has:

![image](https://github.com/dolthub/hosted-issues/assets/3813929/fd756916-a382-40b9-ba92-64a4184a089f)

**Describe alternatives you've considered**
Asking everyone to remember to delete branches after PR's are accepted and merged

**Comment by tbantle22** [comment]
This setting is now available in your deployment's workbench settings 
<img width="1178" alt="Screenshot 2023-09-13 at 11 03 46 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/ad9572f1-2f63-4ad5-a9b2-b46ba43bc1c8">
