### ISSUE TITLE
Deployment > Monitoring - Provide option for more detailed Time Range filtering

### ISSUE THREAD

**Issue by pannelljr** [dolthub/hosted-issues#135]
Currently, the Time Range filter is limited to 8 predefined time periods maxing out at 2 weeks into the past from the time of filter selection. It would be valuable to have the option to custom define the time period (start/end datetime).

**Comment by tbantle22** [comment]
You can now choose a custom time range for the monitoring graphs
<img width="1527" alt="Screenshot 2023-09-22 at 11 10 18 AM" src="https://github.com/dolthub/hosted-issues/assets/29443194/cde25ae2-39d5-4fbc-bc64-df2f21e3a649">
