### ISSUE TITLE
home page horizontal scrolling bar

### ISSUE THREAD

**Issue by liuliu-dev** [dolthub/hosted-issues#30]
the scrolling bar position is off

![Screen Shot 2022-07-26 at 3 01 00 PM](https://user-images.githubusercontent.com/6688812/181120087-46cf005e-2300-465d-a0c9-e8cdcf065355.png)

**Comment by tbantle22** [comment]
This is just on dev. I'll fix

**Comment by tbantle22** [comment]
Have a fix for this in my current PR. Is on dev now
