### ISSUE TITLE
Error calling dolt_clone from a hosted instance

### ISSUE THREAD

**Issue by tbantle22** [dolthub/hosted-issues#31]
When I connect to a sql server from hosted and then try to call dolt_clone I get this error.
```
mysql> use coronavirus;
Database changed
mysql> call dolt_clone("dolthub/corona-virus");
ERROR 1105 (HY000): unable to clone remote database; no remote dialer configured
```
It's possible the port to clone is not open on the hosted instance

**Comment by fulghum** [comment]
I wasn't able to repro this before, but just figured it out... 

When a Dolt sql-server starts up with no databases, you currently see this error after you create a database, use it, and call `dolt_clone`. However... if you stop the server and restart it, then `dolt_clone` works as expected. This seems to be something related to how we initialize the database provider and must not be setting the remote dialer.

**Comment by fulghum** [comment]
Found it! The provider's RemoteDialer comes from `MultiRepoEnv.RemoteDialProvider`, and that code just grabs the remote dialer from the first DoltEnv, otherwise returns nil if there aren't any DoltEnvs. I'll see if we can fake enough of a DoltEnv in that case to make the dialer work.
