### ISSUE TITLE
Allow users to specify a service window

### ISSUE THREAD

**Issue by bheni** [dolthub/hosted-issues#45]
**Is your feature request related to a problem? Please describe.**
In order to be able to update hosted instances at times that do not impact applications, users should be able to specify a service window where they are ok taking short amounts of downtime while we update software.

**Describe the solution you'd like**
Somewhere on the deployments page a user should be able to specify a day of week and time window of at least 30 minutes where we can update software as needed.

**Comment by tbantle22** [comment]
You can now configure your settings window in the settings tab of your deployment
