### ISSUE TITLE
Hosted Configuration

### ISSUE THREAD

**Issue by bheni** [dolthub/hosted-issues#47]
**Is your feature request related to a problem? Please describe.**
Currently the configuration for each hosted instance is the same for all builds.  We should provide more control to the users.

**Describe the solution you'd like**
Whether it be some kind of editor, or a form with drop downs we should allow a user to configure a bunch of the settings that are set in the config.yaml file.

**Comment by tbantle22** [comment]
we already have an issue for this https://github.com/dolthub/hosted-issues/issues/6
