### ISSUE TITLE
Dolt version upgrades

### ISSUE THREAD

**Issue by timsehn** [dolthub/hosted-issues#5]
How are we going to do these?

**Comment by timsehn** [comment]
I think we start manually.

'Actions > Change Dolt Version' on the deployment page. You should be able to pick a version, and it goes into "upgrading" state, and then back to started once it is restarted.

**Comment by tbantle22** [comment]
You can upgrade the Dolt version from 'Actions -> Update Dolt Version' now. This uses the approved Dolt version, which is set by our team. Eventually we should provide a list of dolt versions to choose from
