### ISSUE TITLE
Send email invites to unregistered collaborators

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#77]
A customer using the Hosted Dolt web UI wanted to add a an individual collaborator to a deployment, but wasn't sure how to invite them to join Hosted Dolt and the current UI only shows individuals who have already registered with Hosted Dolt. 

It would be nice to make it clearer in the UI that you can only add individuals or teams who are already registered with Hosted Dolt, and also provide a button to send an email invitation to an individual, inviting them to sign up for Hosted Dolt. Ideally, we would track that this deployment invited that individual and add them as a collaborator once they sign up, so that the administrator doesn't have to come back and add them again after inviting them.

**Comment by tbantle22** [comment]
You can now add collaborators by email. It will either add the user associated with that email or prompt an unregistered email to create an account and they will be automatically added as a collaborator when their account is created

<img width="572" alt="Screen Shot 2023-05-23 at 1 23 10 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/d25fee57-8ca3-4067-ae13-1051f79417af">
