### ISSUE TITLE
Add dolt version number to "My Deployments" page

### ISSUE THREAD

**Issue by jacobATcertifiedfoodDotinfo** [dolthub/hosted-issues#83]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Please add the dolt version number of each deployment to this page: https://hosted.doltdb.com/deployments 

**Describe alternatives you've considered**
N/A

**Additional context**
Since dolt releases new versions frequently, checking the dolt version of all deployments on one page is a time saver.

**Comment by tbantle22** [comment]
This is going to production right now
