### ISSUE TITLE
Upload a file to a table 

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#96]
A Hosted Dolt customer would like to have the same file upload support in Hosted Dolt as we have on DoltHub. 

When clicking the pencil icon to edit a table, DoltHub gives you a choice of running SQL queries, using the spreadsheet editor, or uploading a file (with various upload options). This customer would like the same option available for Hosted Dolt.

**Comment by tbantle22** [comment]
Just released a V1 of file upload for the workbench. You can access it my clicking on the `Add` dropdown in the database nav or my clicking on the pencil icon to edit a table. It uses [`LOAD DATA`](https://dev.mysql.com/doc/refman/8.0/en/load-data.html) to do the import so the functionality is a little different from file upload on DoltHub.

Next I'll be adding the spreadsheet editor and support more LOAD DATA options (like ignore and replace)

**Comment by tbantle22** [comment]
Spreadsheet editor is now available to insert new rows into a table
<img width="931" alt="Screen Shot 2023-05-31 at 1 22 05 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/d4e2bf75-3e44-4863-803d-a170d6ceff5f">

**Comment by tbantle22** [comment]
Deployments with Dolt versions 1.3.0 or greater can now choose how to handle duplicate keys for the import (ignore or replace)
<img width="687" alt="Screen Shot 2023-06-06 at 2 28 20 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/d332bb23-247d-4596-b3a2-99623565112d">
