### ISSUE TITLE
Download CSV export for table or query

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#97]
A Hosted Dolt customer would like the same support for downloading query results that we have on DoltHub, to be available on Hosted Dolt. 

They would like to open the workbench for their Hosted Dolt deployment, run a query, then use the same drop down actions as on DoltHub to download the full results to a CSV.

**Comment by tbantle22** [comment]
This is now available on the Hosted workbench from the Options dropdown above the sql results table
