### ISSUE TITLE
not able to clone hosted.dolthub database

### ISSUE THREAD

**Issue by subhra78** [dolthub/hosted-issues#98]
Hi 
`cause: could not access dolt url 'https://hosted.doltdb.com/deployments/myoranization/dev-dolthub/database/my_database': rpc error: code = Unimplemented desc = `
getting this error when trying to close database from hosted dolthub , any help?

**Comment by subhra78** [comment]
Also, wanted to know why csv upload and spreadsheet is not there in hosted dolthub? Is there any reason or it's a bug?

**Comment by timsehn** [comment]
What is the clone command you are trying to run? Can you send a screenshot of the clone section of the connectivity page?

**Comment by timsehn** [comment]
I helped debug on Discord and it seemed @subhra78 did not create a deployment with WebPKI enabled. He is testing that fix now.
