### ISSUE TITLE
Easily enable automatic Dolt commits via `@@dolt_transaction_commit`

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#99]
A customer is working on integrating Hosted Dolt into some of their existing systems. Some of these systems want to directly use Dolt's versioning features, but many others just want to interact with Hosted Dolt as if it were a normal MySQL database. The customer would like those interactions to still create Dolt commits. They were unaware of the `@@dolt_transaction_commit` setting that automatically creates Dolt commits from SQL commits and thought this would be an excellent fit for them. Since this feature is so useful for them, and likely for other customers who don't know about it yet, they asked us to consider making it more prominent in the UI. 

One suggestion was to expose `@@dolt_transaction_commit` from a Hosted Dolt Deployment configuration section, just like we do for `@@autocommit`. _(It would be nice to have a short snippet of description for each configuration item, btw, or at least a link to more documentation.)_
<img width="383" alt="Screen Shot 2023-05-23 at 3 04 14 PM" src="https://github.com/dolthub/hosted-issues/assets/193449/6aa5efe8-938f-4708-a13b-ea27760996f4">

It might also be interesting to consider showing it to customer upfront during the deployment creation, but I don't want to make the launch wizard more complex than it needs to be.

**Comment by tbantle22** [comment]
I added help popups with config item descriptions
<img width="658" alt="Screen Shot 2023-05-23 at 4 35 24 PM" src="https://github.com/dolthub/hosted-issues/assets/29443194/bca97a41-9bff-4ef0-a247-1018959671ec">

**Comment by tbantle22** [comment]
This is now available when you upgrade the Dolt version of your instance to 1.2.0
